# baseURL = ''
languageCode = 'zh'
# ğŸ’¡: æ–‡æ¡£åå­—
title = 'å¼€æºæ“ä½œç³»ç»Ÿç¤¾åŒº(os2c, Open Source Operating System Community)'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy']

[markup.tableOfContents]
  startLevel = 1

[[menu.after]]
  name = 'ä»“åº“åœ°å€'
  # ğŸ’¡: æ–‡æ¡£ä»“åº“åœ°å€
  url = 'https://github.com/os2c/os2c.github.io'
  weight = 10

[params]
  BookTheme = 'auto'
  BookSection = '*'
  # ğŸ’¡: æ–‡æ¡£ä»“åº“åœ°å€
  BookRepo = 'https://github.com/os2c/os2c.github.io'
  BookEditPath = 'edit/main'
  BookCommitPath = 'commit'
  BookDateFormat = 'Jan 2, 2006'
