# baseURL = ''
languageCode = 'zh'
# ğŸ’¡: æ–‡æ¡£åå­—
title = 'xxx çš„æ–‡æ¡£'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy']

[markup.tableOfContents]
  startLevel = 1

[[menu.after]]
  name = 'ä»“åº“åœ°å€'
  # ğŸ’¡: æ–‡æ¡£ä»“åº“åœ°å€
  url = 'https://github.com/kern-crates/hugo-book-template'
  weight = 10

[params]
  BookTheme = 'auto'
  BookSection = '*'
  # ğŸ’¡: æ–‡æ¡£ä»“åº“åœ°å€
  BookRepo = 'https://github.com/kern-crates/hugo-book-template'
  BookEditPath = 'edit/main'
  BookCommitPath = 'commit'
  BookDateFormat = 'Jan 2, 2006'
